---
title: "LINEAR REGRESSION"
output: html_notebook
by: João Ataíde
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(warning = FALSE, message = FALSE)
#knitr::opts_knit$set(root.dir = "D:/Estudos/Stanford/Statistical Learning")
```

```{r, include=FALSE}
#.libPaths(c("C:\\Users\\jv_at\\R", "C:\\Users\\jv_at\\R"))
#R_LIBS_SITE="C:\\Users\\jv_at\\R"
```

```{r install lib MASS}
install.packages("MASS")
```
```{r install lib ISLR}
install.packages("ISLR")
```

```{r load librarys}
library(MASS)
library(ISLR)
```

```{r}
names(Boston)
```

```{r duvidas}
?Boston
```

```{r }
plot(medv ~ lstat, data = Boston)
```

```{r}
fit1 = lm(medv~lstat, data = Boston)
fit1
```

```{r}
summary(fit1)
```

```{r}
plot(medv ~ lstat, data = Boston)
abline(fit1, col = 'red')
```

```{r}
names(fit1)
```

```{r}
confint(fit1)
```

```{r}
predict(fit1, data.frame(lstat = c(5, 10, 15)), interval = "confidence")
```

## Multiple Linear Regression
```{r}
fit2 = lm(medv~lstat + age, data = Boston)
fit2
```

```{r}
summary(fit2)
```

```{r}
fit3 = lm(medv~., Boston)
fit3
```

```{r}
summary(fit3)
```

```{r}
par(mfrow=c(2,2))
plot(fit3)
```

```{r}
fit4 = update(fit3, ~., -age-indus)
```

```{r}
summary(fit4)
```

```{r}
par(mfrow=c(2,2))
plot(fit4)
```

##Nonlinear terms and Interaction
```{r}
fit5 = lm(medv~lstat*age, Boston)
```
```{r}
summary(fit5)
```
```{r}
fit6 = lm(medv~lstat + I(lstat^2), Boston)
```
```{r}
summary(fit6)
```
```{r}
attach(Boston)
```
```{r}
par(mfrow = c(1,1))
plot(medv~lstat)
points(lstat, fitted(fit6), col = "red", pch = 20)
```
```{r}
fit7 = lm(medv~poly(lstat, 4))
```
```{r}
par(mfrow = c(1,1))
plot(medv~lstat)
points(lstat, fitted(fit6), col = "red", pch = 20)
points(lstat, fitted(fit7), col = "blue", pch = 20)
```
```{r}
par(mfrow = c(1,1))
plot(medv~lstat)
points(lstat, fitted(fit6), col = "red", pch = 20)
points(lstat, fitted(fit7), col = "blue", pch = 20)
plot(1:20, 1:20, pch = 1:20, cex = 2)
```
##Qualitative predictions
```{r}
names(Carseats)
```
```{r}
summary(Carseats)
```
```{r}
fit11 = lm(Sales~. + Income:Advertising + Age:Price, Carseats)
fit11
```
```{r}
summary(fit11)
```
```{r}
contrasts(Carseats$ShelveLoc)
```
```{r}
#create R function
regplot = function(x, y){
  fit = lm(y~x)
  plot(x, y)
  abline(fit, col = 'red')
}
```

```{r}
regplot(Carseats$Price, Carseats$Sales)
```
```{r}
#create R function
regplot = function(x, y,...){
  fit = lm(y~x)
  plot(x, y,...)
  abline(fit, col = 'red')
}

```
```{r}
regplot(Carseats$Price, Carseats$Sales, xlab = "Price", ylab="Sales", cal = "blue", pch = 20)
```
