---
title: "RESAMPLING"
output: html_notebook
by: João Ataíde
---

```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "D:/Estudos/Stanford/Statistical Learning 2")
```


```{r}
.libPaths(c("D:\\Estudos\\Stanford\\Statistical Learning 2\\env", "D:\\Estudos\\Stanford\\Statistical Learning 2\\env"))
R_LIBS_SITE="D:\\Estudos\\Stanford\\Statistical Learning 2\\env"
```

```{r}
#install.packages("ISLR2")
#install.packages("boot")
#install.packages("MASS")
```
```{r}
library(ISLR2)
library(boot)
library(MASS)
```
```{r}
?cv.glm
```
```{r}
plot(mpg ~ horsepower, data = Auto)
```
```{r LOOCV}
glm.fit = glm(mpg ~ horsepower, data = Auto)
gml.fit
```
```{r}
cv.err = cv.glm(Auto, glm.fit)
cv.err$delta
```
```{r}
cv.error = rep(0, 10)
for (i in 1:10) {
  glm.fit = glm(mpg ~ poly(horsepower, i), data = Auto)
  cv.error[i] = cv.glm(Auto, glm.fit)$delta[1]
}
cv.error
```
```{r}
set.seed(17)


cv.error.10 = rep(0, 10)
for (i in 1:10) {
  glm.fit = glm(mpg ~ poly(horsepower, i), data = Auto)
  cv.error.10[i] = cv.glm(Auto, glm.fit, K = 10)$delta[1]
}

cv.error.10
```


## The Bootstrap
```{r}
alpha.fn = function(data, index) {
  X <- data$X[index]
  Y <- data$Y[index]
  (var(Y) - cov(X, Y)) / (var(X) + var(Y) - 2 * cov(X, Y))
}
```

```{r}
alpha.fn(Portfolio, 1:100)
```

```{r}
alpha.fn(Portfolio, sample(100, 100, replace = T))
```
```{r}
###
boot(Portfolio, alpha.fn, R = 1000)
```
### Estimating the Accuracy of a Linear Regression Model
```{r}
boot.fn = function(data, index)
  coef(lm(mpg ~ horsepower, data = data, subset = index))
boot.fn(Auto, 1:392)
```
```{r}
boot.fn(Auto, sample(392, 392, replace = T))
boot.fn(Auto, sample(392, 392, replace = T))
```
```{r}
boot(Auto, boot.fn, 1000)
```
```{r}
summary(lm(mpg ~ horsepower, data = Auto))$coef
```
```{r}
boot.fn = function(data, index)
  coef(
    lm(mpg ~ horsepower + I(horsepower^2),
       data = data, subset = index)
  )
```
```{r}
set.seed(1)
boot(Auto, boot.fn, 1000)
summary(lm(mpg ~ horsepower + I(horsepower^2), data = Auto))$coef
```
